[package]
name = "gpui-component-story"
version = "0.5.1"
publish = false
edition = "2024"

[dependencies]
anyhow = "1"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "x11", "wayland", "runtime_shaders"] }
gpui-component = { path = "../ui" }
gpui-component-assets = { path = "../assets" }
reqwest_client = { git = "https://github.com/zed-industries/zed" }
smol = "2"
tracing = "0.1.41"
rust-i18n = "3"

autocorrect = "2.14.2"
chrono = "0.4"
csv = "1.4"
fake = { version = "2.10.0", features = ["dummy"] }
itertools = "0.14.0"
lsp-types = { version = "0.97.0", features = ["proposed"] }
rand = "0.8"
regex = "1"
serde = "1"
serde_json = "1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt", "registry"], default-features = false }
unindent = "0.2.3"
dirs = "6.0.0"

# Native-only dependencies (not available on WASM)
[target.'cfg(not(target_family = "wasm"))'.dependencies]
tree-sitter-navi = "0.2.2"
color-lsp = "0.2.0"

[target.'cfg(target_family = "wasm")'.dependencies]
gpui_web = { git = "https://github.com/zed-industries/zed" }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.18" }